node {
    stage('Build') {
        sh "docker build -t getting-started ."
 
    }

    stage('Run Container') {
        sh "docker run -t -d -p 3000:3000 --name getting-started "    
        
       
    }

    stage('Verify Running App') {      
        sh "docker ps | grep getting-started"
       
    }
}
