node {

    stage('Checkout') {
    checkout scm
}


    stage('Opkuisen') {
        catchError(buildResult: 'SUCCESS') {
            echo 'Opkuisen oude containers/images'
            sh 'docker stop samplerunning || true'
            sh 'docker rm samplerunning || true'
            sh 'docker rmi sampleapp || true'
            sh 'rm -rf tempdir'
        }
    }


    stage('Build') {
        echo 'Image maken'
        sh 'docker build -t sampleapp ./cicd-sample-app'
    }

    stage('Docker runnen') {
        echo 'Container runnen'
        sh 'docker run -d -p 5050:5050 --name samplerunning sampleapp'
        sh 'docker ps -a'
    }

    stage('Tests') {
        echo 'Curl om te testen'
        sh 'sleep 5'
        sh 'curl -f http://192.168.56.20:5050 || echo "Check of de container wel draait"'
    }
}
